# -*- coding: utf-8 -*-
"""final_publish.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1whSbfio_bzBXyrkekOWIVUlodXl8xb9h
"""

#!/usr/bin/env python3
# license removed for
import rospy
from std_msgs.msg import Int64

def talker():
    rospy.init_node('start', anonymous=True)
    pub = rospy.Publisher('std_id', Int64, queue_size=10)
    
    rate = rospy.Rate(5)
    while not rospy.is_shutdown():
        ros = 6352500404
        rospy.loginfo(ros)
        pub.publish(ros)
        rate.sleep()

if _name_ == '_main_':
     try:
        talker()
     except rospy.ROSInterruptException:
        pass

#!/usr/bin/env python3
import rospy
from std_msgs.msg import Int64

def callback(sub_data):
    input_data = sub_data.data
    print(input_data)
    
def listener():

    
    rospy.init_node('end', anonymous=True)

    rospy.Subscriber("std_id", Int64, callback)
    rospy.spin()

if _name_ == '_main_':
    listener()